# fly.toml app configuration file generated for studi2024-crimson-hill-5228 on 2025-03-27T19:06:39+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'studi2024-crimson-hill-5228'
primary_region = 'fra'
console_command = '/code/Studi_/manage.py shell'

[deploy]
  release_command = 'python Studi_/manage.py migrate --noinput'

#[http_service]
#  internal_port = 8000
#  force_https = true
#  auto_stop_machines = 'stop'
#  auto_start_machines = true
#  min_machines_running = 0
#  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1

# Uncomment and use the following for 5.7:
[processes]
  app = "--datadir /data/mysql"

[mounts]
  source = "mysqldata"
  destination = "/data"

[env]
  PORT = '5432'
  MYSQL_DATABASE = "studidb"
  MYSQL_USER = "postgres"

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
