# Generated by Django 5.0.4 on 2024-04-21 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='anniversary',
            field=models.DateField(null=True),
        ),
    ]
