# Generated by Django 5.0.4 on 2024-04-21 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('joapp', '0002_utilisateur_anniversary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='utilisateur',
            old_name='anniversary',
            new_name='anniversaire',
        ),
    ]
