# Generated by Django 5.0.4 on 2024-04-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joapp', '0003_rename_anniversary_utilisateur_anniversaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='numero_telephone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='utilisateur',
            name='prenom',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
