# Generated by Django 5.0.4 on 2024-04-21 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joapp', '0004_utilisateur_email_utilisateur_numero_telephone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='confirmation_mot_de_passe',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='mot_de_passe',
            field=models.CharField(max_length=128),
        ),
    ]
