# Generated by Django 5.0.4 on 2024-04-21 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('joapp', '0005_utilisateur_confirmation_mot_de_passe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='anniversaire',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='confirmation_mot_de_passe',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='email',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='numero_telephone',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='prenom',
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='mot_de_passe',
            field=models.CharField(max_length=50),
        ),
    ]
